/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;



/**
 *
 * @author Dell
 */
public class CandidateMainPage extends javax.swing.JFrame {

    /**
     * Creates new form CandidateMainPage
     */
    
    public CandidateMainPage() {
        initComponents();
        this.setSize(900, 900);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    String name;
    String email;
    ArrayList<JPanel> pn=new <JPanel>ArrayList();
    public void hideOtherPanels()
    {
        Iterator<JPanel> pan=pn.iterator();
        while(pan.hasNext()){
            JPanel jPanel=pan.next();
            jPanel.setVisible(false);
            this.remove(jPanel);
        }
    }
    public void setCandidateName(String name,String email)
    {
        this.name=name;
        this.email=email;
        this.hideOtherPanels();
        CandidateTestDisplay l1=new CandidateTestDisplay();
        l1.setCandidateName(name,email,this);
        l1.setBounds(0,0,824,580);
        this.pn.add(l1);
        this.add(l1);
        
        this.revalidate();
        this.repaint();
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CandidatePageMenuBar = new javax.swing.JMenuBar();
        CandidateOptionMenu = new javax.swing.JMenu();
        CandidateDetailsMenuItem = new javax.swing.JMenuItem();
        CandidateLogoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CandidateOptionMenu.setText("Options");

        CandidateDetailsMenuItem.setText("Change Details");
        CandidateDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateDetailsMenuItemActionPerformed(evt);
            }
        });
        CandidateOptionMenu.add(CandidateDetailsMenuItem);

        CandidateLogoutMenuItem.setText("Logout");
        CandidateLogoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateLogoutMenuItemActionPerformed(evt);
            }
        });
        CandidateOptionMenu.add(CandidateLogoutMenuItem);

        CandidatePageMenuBar.add(CandidateOptionMenu);

        setJMenuBar(CandidatePageMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CandidateDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateDetailsMenuItemActionPerformed
          this.hideOtherPanels();
          CandidateUpdate c1=new CandidateUpdate();
          c1.setEmail(this.email,this,this.name);
          add(c1);
          this.pn.add(c1);
          c1.setBounds(0,0,400,400);
          this.setSize(500, 500);
          this.revalidate();
          this.repaint();
    }//GEN-LAST:event_CandidateDetailsMenuItemActionPerformed

    private void CandidateLogoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateLogoutMenuItemActionPerformed
        LoginScreen loginScreen=new LoginScreen();
        loginScreen.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CandidateLogoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateMainPage().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CandidateDetailsMenuItem;
    private javax.swing.JMenuItem CandidateLogoutMenuItem;
    private javax.swing.JMenu CandidateOptionMenu;
    private javax.swing.JMenuBar CandidatePageMenuBar;
    // End of variables declaration//GEN-END:variables
}
