/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;

/**
 *
 * @author Dell
 */
public class CandidateResultShow extends javax.swing.JFrame {

    /**
     * Creates new form CandidateResultShow
     */
    String email; CandidateSelector sel;
    public CandidateResultShow(String email, CandidateSelector sel) {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setSize(625,429);
        this.setLocationRelativeTo(null);
        this.email=email;
        this.sel=sel;
        try(MongoClient mongo=new MongoClient("localhost",27017)){
            DB db=mongo.getDB("rpu");
            DBCollection qlrresult=db.getCollection("qlrresult");
            DBCollection cjavaresult=db.getCollection("cjavaresult");
            DBCollection frameresult=db.getCollection("frameresult");
            DBCollection andresult=db.getCollection("andresult");
            DBCollection cand=db.getCollection("candidatelogin");
            BasicDBObject bdo=new BasicDBObject().append("EmailID",email);
            DBCursor qlrcursor=qlrresult.find(bdo);
            DBCursor cjavacursor=cjavaresult.find(bdo);
            DBCursor frmcursor=frameresult.find(bdo);
            DBCursor andcursor=andresult.find(bdo);
            DBCursor cur=cand.find(bdo);
            DBObject d1=cur.next();
            CandidateNameLabel.setText(d1.get("First_Name").toString()+" "+d1.get("Last_Name"));
            while(qlrcursor.hasNext())
            {
                QLRResult.setText(qlrcursor.next().get("Percentage").toString());
                break;
            }
            while(cjavacursor.hasNext())
            {
                CJavaLabel.setText(cjavacursor.next().get("Percentage").toString());
                break;
            }
            while(frmcursor.hasNext())
            {
                FrameResult.setText(frmcursor.next().get("Percentage").toString());
                break;
            }
            while(andcursor.hasNext())
            {
                AndroidResult.setText(andcursor.next().get("Percentage").toString());
                break;
            }
            qlrcursor.close();
            cjavacursor.close();
            frmcursor.close();
            andcursor.close();
        }
    }
    MongoClient mongo; DB db; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CandidateNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        QLRResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CJavaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FrameResult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AndroidResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CandidateNameLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        CandidateNameLabel.setForeground(new java.awt.Color(0, 0, 255));
        CandidateNameLabel.setText("Candidate Name");

        jLabel1.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabel1.setText("QLR Result:");

        QLRResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        QLRResult.setText("Not Appeared");

        jLabel3.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabel3.setText("Core Java Result:");

        CJavaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CJavaLabel.setText("Not Appeared");

        jLabel4.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabel4.setText("Frameworks Result:");

        FrameResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FrameResult.setText("Not Appeared");

        jLabel5.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabel5.setText("Android Result:");

        AndroidResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AndroidResult.setText("Not Appeared");

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AndroidResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CJavaLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(FrameResult)))))
                .addGap(0, 121, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QLRResult))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(CandidateNameLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLRResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CJavaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrameResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AndroidResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               sel.setVisible(true);
               this.setVisible(false);
                this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateResultShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateResultShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateResultShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateResultShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateResultShow().setVisible(true);
            }
        }); 
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AndroidResult;
    private javax.swing.JLabel CJavaLabel;
    private javax.swing.JLabel CandidateNameLabel;
    private javax.swing.JLabel FrameResult;
    private javax.swing.JLabel QLRResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
