/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CandidateTestDisplay extends javax.swing.JPanel {

    /**
     * Creates new form CandidateTestDisplay
     */
    public CandidateTestDisplay() {
        initComponents();
    }
    String email;int countq=0,countc=0,countf=0,counta=0; JFrame j1;
    public void setCandidateName(String name,String email,JFrame j1)
    {
        CoreJavaButton.setEnabled(false);
        JavaFrameworkButton.setEnabled(false);
        AndroidButton.setEnabled(false);
        this.j1=j1;
        String perc=new String();
        this.email=email;
        WelcomeLabel.setText("Welcome "+name);
        try (MongoClient mongoClient = new MongoClient("localhost",27017)) {
            DB db=mongoClient.getDB("rpu");
            DBCollection qlrresult=db.getCollection("qlrresult");
            DBCollection cjavaresult=db.getCollection("cjavaresult");
            DBCollection frmresult=db.getCollection("frameresult");
            DBCollection andresult=db.getCollection("andresult");
            BasicDBObject dbo=new BasicDBObject().append("EmailID",email);
            DBCursor qlrcursor=qlrresult.find(dbo);
            DBCursor cjavacursor=cjavaresult.find(dbo);
            DBCursor frmcursor=frmresult.find(dbo);
            DBCursor andcursor=andresult.find(dbo);
            while(qlrcursor.hasNext())
            {
                perc=String.valueOf(qlrcursor.next().get("Percentage"));
                countq++;
            }   if(countq!=0)
            {
                
                QLRResultLabel.setText(perc);
            }   while(cjavacursor.hasNext())
            {
                perc=String.valueOf(cjavacursor.next().get("Percentage"));
                countc++;
            }   if(countc!=0)
            {
                
                CoreJavaResultLabel.setText(perc);
            }   while(frmcursor.hasNext())
            {
                perc=String.valueOf(frmcursor.next().get("Percentage"));
                countf++;
            }   if(countf!=0)
            {
                
                JavaFrameworkResultLabel.setText(perc);
            }   while(andcursor.hasNext())
            {
                perc=String.valueOf(andcursor.next().get("Percentage"));
                counta++;
            }   if(counta!=0)
            {
                
                AndroidResultLabel.setText(perc);
            }   double percq=0.0f,percc=0.0f,percf=0.0f;
            if(QLRResultLabel.getText().equals("None")==false)
                percq=Double.parseDouble(QLRResultLabel.getText());
            if(CoreJavaResultLabel.getText().equals("None")==false)
                percc=Double.parseDouble(CoreJavaResultLabel.getText());
            if(JavaFrameworkResultLabel.getText().equals("None")==false)
                percf=Double.parseDouble(JavaFrameworkResultLabel.getText());
            if(percq >= 40.0)
            {
                CoreJavaButton.setEnabled(true);
            }   if(percc >= 40.0)
            {
                JavaFrameworkButton.setEnabled(true);
            }   if(percf >= 40.0)
            {
                AndroidButton.setEnabled(true);
            }   qlrcursor.close();
            cjavacursor.close();
            frmcursor.close();
            andcursor.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QLRTestButton = new javax.swing.JButton();
        AndroidResultLabel = new javax.swing.JLabel();
        QLRPreviousLabel = new javax.swing.JLabel();
        QLRResultLabel = new javax.swing.JLabel();
        CoreJavaButton = new javax.swing.JButton();
        CoreJavaPreviousLabel = new javax.swing.JLabel();
        CoreJavaResultLabel = new javax.swing.JLabel();
        JavaFrameworkButton = new javax.swing.JButton();
        JAVAFrameworkPreviousLabel = new javax.swing.JLabel();
        JavaFrameworkResultLabel = new javax.swing.JLabel();
        AndroidButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        QLRTestButton.setBackground(new java.awt.Color(153, 204, 255));
        QLRTestButton.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        QLRTestButton.setForeground(new java.awt.Color(0, 0, 153));
        QLRTestButton.setText("Basic QLR Test");
        QLRTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLRTestButtonActionPerformed(evt);
            }
        });
        add(QLRTestButton);
        QLRTestButton.setBounds(10, 90, 780, 38);

        AndroidResultLabel.setFont(new java.awt.Font("LilyUPC", 0, 36)); // NOI18N
        AndroidResultLabel.setText("None");
        add(AndroidResultLabel);
        AndroidResultLabel.setBounds(170, 530, 166, 34);

        QLRPreviousLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QLRPreviousLabel.setText("Previous Result:");
        add(QLRPreviousLabel);
        QLRPreviousLabel.setBounds(60, 160, 98, 17);

        QLRResultLabel.setFont(new java.awt.Font("LilyUPC", 0, 36)); // NOI18N
        QLRResultLabel.setText("None");
        add(QLRResultLabel);
        QLRResultLabel.setBounds(160, 150, 166, 34);

        CoreJavaButton.setBackground(new java.awt.Color(153, 204, 255));
        CoreJavaButton.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        CoreJavaButton.setForeground(new java.awt.Color(0, 0, 153));
        CoreJavaButton.setText("Core JAVA Test");
        CoreJavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoreJavaButtonActionPerformed(evt);
            }
        });
        add(CoreJavaButton);
        CoreJavaButton.setBounds(10, 210, 780, 35);

        CoreJavaPreviousLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CoreJavaPreviousLabel.setText("Previous Result:");
        add(CoreJavaPreviousLabel);
        CoreJavaPreviousLabel.setBounds(60, 280, 98, 17);

        CoreJavaResultLabel.setFont(new java.awt.Font("LilyUPC", 0, 36)); // NOI18N
        CoreJavaResultLabel.setText("None");
        add(CoreJavaResultLabel);
        CoreJavaResultLabel.setBounds(160, 270, 166, 36);

        JavaFrameworkButton.setBackground(new java.awt.Color(153, 204, 255));
        JavaFrameworkButton.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        JavaFrameworkButton.setForeground(new java.awt.Color(0, 0, 153));
        JavaFrameworkButton.setText("JAVA Frameworks Test");
        JavaFrameworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaFrameworkButtonActionPerformed(evt);
            }
        });
        add(JavaFrameworkButton);
        JavaFrameworkButton.setBounds(10, 334, 780, 35);

        JAVAFrameworkPreviousLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JAVAFrameworkPreviousLabel.setText("Previous Result:");
        add(JAVAFrameworkPreviousLabel);
        JAVAFrameworkPreviousLabel.setBounds(60, 410, 98, 17);

        JavaFrameworkResultLabel.setFont(new java.awt.Font("LilyUPC", 0, 36)); // NOI18N
        JavaFrameworkResultLabel.setText("None");
        add(JavaFrameworkResultLabel);
        JavaFrameworkResultLabel.setBounds(160, 400, 166, 38);

        AndroidButton.setBackground(new java.awt.Color(153, 204, 255));
        AndroidButton.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        AndroidButton.setForeground(new java.awt.Color(0, 0, 153));
        AndroidButton.setText("Android Test");
        AndroidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndroidButtonActionPerformed(evt);
            }
        });
        add(AndroidButton);
        AndroidButton.setBounds(10, 470, 780, 35);

        WelcomeLabel.setFont(new java.awt.Font("Nyala", 0, 36)); // NOI18N
        WelcomeLabel.setText("Welcome");
        add(WelcomeLabel);
        WelcomeLabel.setBounds(208, 11, 350, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Previous Result:");
        add(jLabel5);
        jLabel5.setBounds(70, 540, 98, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void QLRTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLRTestButtonActionPerformed
            if(countq==0)
            {
            QuizFrame q1=new QuizFrame();
            q1.decideWhichTest("qlr",this.email);
            q1.setVisible(true);
            this.setVisible(false);
            this.j1.setVisible(false);
            this.j1.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Already Appeared!");
            
            }// TODO add your handling code here:
    }//GEN-LAST:event_QLRTestButtonActionPerformed

    private void CoreJavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoreJavaButtonActionPerformed
        if(countc==0)
            {
            QuizFrame q1=new QuizFrame();
            q1.decideWhichTest("cjava",this.email);
            q1.setVisible(true);
            this.setVisible(false);
            this.j1.setVisible(false);
            this.j1.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Already Appeared!");
            
            }// TODO add your handling code here:
    }//GEN-LAST:event_CoreJavaButtonActionPerformed

    private void JavaFrameworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaFrameworkButtonActionPerformed
                if(countf==0)
            {
            QuizFrame q1=new QuizFrame();
            q1.decideWhichTest("frame",this.email);
            q1.setVisible(true);
            this.setVisible(false);
            this.j1.setVisible(false);
            this.j1.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Already Appeared!");
            
            }        // TODO add your handling code here:
    }//GEN-LAST:event_JavaFrameworkButtonActionPerformed

    private void AndroidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndroidButtonActionPerformed
                if(counta==0)
            {
            QuizFrame q1=new QuizFrame();
            q1.decideWhichTest("android",this.email);
            q1.setVisible(true);
            this.setVisible(false);
            this.j1.setVisible(false);
            this.j1.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Already Appeared!");
            
            } // TODO add your handling code here:
    }//GEN-LAST:event_AndroidButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndroidButton;
    private javax.swing.JLabel AndroidResultLabel;
    private javax.swing.JButton CoreJavaButton;
    private javax.swing.JLabel CoreJavaPreviousLabel;
    private javax.swing.JLabel CoreJavaResultLabel;
    private javax.swing.JLabel JAVAFrameworkPreviousLabel;
    private javax.swing.JButton JavaFrameworkButton;
    private javax.swing.JLabel JavaFrameworkResultLabel;
    private javax.swing.JLabel QLRPreviousLabel;
    private javax.swing.JLabel QLRResultLabel;
    private javax.swing.JButton QLRTestButton;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
