/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.JOptionPane;


/**
 *
 * @author Dell
 */
public class CandidateLogin extends javax.swing.JPanel {

    /**
     * Creates new form CandidateLogin
     */
    String name;
    String email;
    int count=1;
    
      
    
    public CandidateLogin(LoginScreen parentFrame) {
        initComponents();
        this.parentFrame=parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLabel = new javax.swing.JLabel();
        LoginTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        LoginLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(51, 0, 102));
        LoginLabel.setLabelFor(LoginTextField);
        LoginLabel.setText("LOGIN ID:");
        add(LoginLabel);
        LoginLabel.setBounds(180, 170, 140, 34);

        LoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextFieldActionPerformed(evt);
            }
        });
        add(LoginTextField);
        LoginTextField.setBounds(330, 170, 212, 34);

        PasswordLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 0, 102));
        PasswordLabel.setLabelFor(PasswordTextField);
        PasswordLabel.setText("PASSWORD:");
        add(PasswordLabel);
        PasswordLabel.setBounds(177, 251, 160, 33);

        LoginButton.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton);
        LoginButton.setBounds(194, 323, 135, 35);

        ClearButton.setFont(new java.awt.Font("Nyala", 0, 24)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        add(ClearButton);
        ClearButton.setBounds(449, 323, 136, 35);
        add(PasswordTextField);
        PasswordTextField.setBounds(347, 251, 213, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/candidate.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextFieldActionPerformed
       
    }//GEN-LAST:event_LoginTextFieldActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
            LoginTextField.setText("");  
            PasswordTextField.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        MongoClient mongoClient=new MongoClient("localhost",27017);
        DB db=mongoClient.getDB("rpu");
        DBCollection coll=db.getCollection("candidatelogin");
        BasicDBObject can=new BasicDBObject("EmailID", LoginTextField.getText());
        can.append("Password",PasswordTextField.getText());
        DBCursor cursor=coll.find(can);
        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            name=(String)obj.get("First_Name");
            email=(String)obj.get("EmailID");
            count=count+1;
            break;
        }
        if(count==1)
        {
            JOptionPane.showMessageDialog(this, "Wrong Credentials!");
            cursor.close();
            mongoClient.close();
        }
        else
        {
            cursor.close();
            mongoClient.close();
            System.out.println(name);
            this.setVisible(false);
            CandidateMainPage m1=new CandidateMainPage();
            m1.setCandidateName(name,email);
            m1.setVisible(true);
            this.parentFrame.setVisible(false);
            this.parentFrame.dispose();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    public LoginScreen parentFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
