/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import com.mongodb.*;
import javax.swing.JOptionPane;
import javax.swing.text.Document;

/**
 *
 * @author Dell
 */
public class CandidateRegisterForm extends javax.swing.JPanel {

    /**
     * Creates new form CandidateRegisterForm
     */
    public CandidateRegisterForm() {
        initComponents();
        RegisteredLabel.setVisible(false);
        
        mongo=new MongoClient("localhost",27017);
        db=mongo.getDB("rpu");
        user=db.getCollection("candidatelogin");
    }
    MongoClient mongo; DB db; DBCollection user;
    public void warn()
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner2 = new javax.swing.JSpinner();
        CandidateRegistrationLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        EmailIDLabel = new javax.swing.JLabel();
        EmailIDTextField = new javax.swing.JTextField();
        Password1Label = new javax.swing.JLabel();
        Password1TextField = new javax.swing.JPasswordField();
        Password2Label = new javax.swing.JLabel();
        Password2TextField = new javax.swing.JPasswordField();
        SelectDegreeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DegreeComboBox = new javax.swing.JComboBox<>();
        FieldLabel = new javax.swing.JLabel();
        FieldComboBox = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        RegisteredLabel = new javax.swing.JLabel();
        EmailComboBox = new javax.swing.JComboBox<String>();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CandidateRegistrationLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CandidateRegistrationLabel.setForeground(new java.awt.Color(51, 51, 255));
        CandidateRegistrationLabel.setText("Candidate Registration");

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FirstNameLabel.setLabelFor(FirstNameTextField);
        FirstNameLabel.setText("First Name:");

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        LastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LastNameLabel.setLabelFor(LastNameTextField);
        LastNameLabel.setText("Last Name:");

        EmailIDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmailIDLabel.setLabelFor(EmailIDLabel);
        EmailIDLabel.setText("Email ID:");

        EmailIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailIDTextFieldKeyTyped(evt);
            }
        });

        Password1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password1Label.setText("Enter new Password:");

        Password1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1TextFieldActionPerformed(evt);
            }
        });

        Password2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password2Label.setText("Confirm Password:");

        SelectDegreeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectDegreeLabel.setText("Select your Graduation Degree:");

        DegreeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.E.", "B.Tech", "B.C.A", "B.C.S" }));
        DegreeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegreeComboBoxActionPerformed(evt);
            }
        });

        FieldLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FieldLabel.setText("Select Field:");

        FieldComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAVA & Frameworks" }));
        FieldComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldComboBoxActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        RegisteredLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisteredLabel.setForeground(new java.awt.Color(51, 204, 0));
        RegisteredLabel.setText("Registered Successfully!");

        EmailComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com","@yahoo.in","@hotmail.com" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(FieldLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(FieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Password1Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Password1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(SelectDegreeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(DegreeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Password2Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Password2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EmailIDLabel)
                                    .addGap(10, 10, 10)
                                    .addComponent(EmailIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EmailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FirstNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LastNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CandidateRegistrationLabel)
                        .addGap(161, 161, 161)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(SubmitButton)
                        .addGap(154, 154, 154)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RegisteredLabel)
                        .addGap(147, 147, 147)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidateRegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FirstNameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailIDLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password1Label)
                    .addComponent(Password1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DegreeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectDegreeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldLabel)
                    .addComponent(FieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(RegisteredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void DegreeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegreeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DegreeComboBoxActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
            FirstNameTextField.setText("") ;
            LastNameTextField.setText("");
            EmailIDTextField.setText("");
            Password1TextField.setText("");
            Password2TextField.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
                String fname,lname,emailuser,email,emailc,pass1,pass2,degree,field;
                fname=FirstNameTextField.getText();
                lname=LastNameTextField.getText();
                emailuser=EmailIDTextField.getText();
                emailc=(String)EmailComboBox.getSelectedItem();
                email=emailuser+emailc;
                pass1=Password1TextField.getText();
                pass2=Password2TextField.getText();
                int i=DegreeComboBox.getSelectedIndex();
                degree=DegreeComboBox.getItemAt(i);
                int j=FieldComboBox.getSelectedIndex();
                field=FieldComboBox.getItemAt(j);
                if(fname.equals("") || lname.equals("") || emailuser.equals("") || pass1.equals("") || pass2.equals(""))
                {
                    JOptionPane.showMessageDialog(this, "All fields are mandatory");
                }
                else
                {
                    BasicDBObject dbo1=new BasicDBObject().append("EmailID",email);
                    DBCursor cor=user.find(dbo1);
                    if(cor.hasNext())
                    {
                        JOptionPane.showMessageDialog(this, "EmailID is already taken");
                    }
                    else
                    {
                        if(pass1.equals(pass2))
                        {
                            BasicDBObject doc=new BasicDBObject("First_Name",fname );
                            doc.append("Last_Name",lname);
                            doc.append("EmailID",email);
                            doc.append("Password",pass1);
                            doc.append("Degree",degree);
                            doc.append("Field",field);
                            user.insert(doc);
                            RegisteredLabel.setVisible(true);
                            mongo.close();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Entered passwords do not match");
                        }
                    }
                }
                
                FirstNameTextField.setText("") ;
                LastNameTextField.setText("");
                EmailIDTextField.setText("");
                Password1TextField.setText("");
                Password2TextField.setText("");
                
                
                // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void FieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldComboBoxActionPerformed

    private void EmailIDTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIDTextFieldKeyTyped
  
    }//GEN-LAST:event_EmailIDTextFieldKeyTyped

    private void Password1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1TextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidateRegistrationLabel;
    private javax.swing.JComboBox<String> DegreeComboBox;
    public javax.swing.JComboBox<String> EmailComboBox;
    private javax.swing.JLabel EmailIDLabel;
    public javax.swing.JTextField EmailIDTextField;
    private javax.swing.JComboBox<String> FieldComboBox;
    private javax.swing.JLabel FieldLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Password1Label;
    private javax.swing.JPasswordField Password1TextField;
    private javax.swing.JLabel Password2Label;
    private javax.swing.JPasswordField Password2TextField;
    private javax.swing.JLabel RegisteredLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SelectDegreeLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
    
}

