/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class companyRegistration extends javax.swing.JPanel {

    /**
     * Creates new form companyRegistration
     */
    public companyRegistration() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        pass2Label = new javax.swing.JLabel();
        pass2TextField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        resetLabel = new javax.swing.JButton();

        setLayout(null);

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(0, 51, 102));
        headingLabel.setText("COMPANY REGISTRATION FORM");
        add(headingLabel);
        headingLabel.setBounds(200, 55, 395, 28);

        nameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nameLabel.setText("Company Name:");
        add(nameLabel);
        nameLabel.setBounds(215, 138, 122, 23);

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField);
        nameTextField.setBounds(341, 139, 212, 22);

        idLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        idLabel.setText("Enter Company ID:");
        add(idLabel);
        idLabel.setBounds(200, 189, 137, 15);
        add(idTextField);
        idTextField.setBounds(341, 187, 212, 20);

        passwordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passwordLabel.setText("Password:");
        add(passwordLabel);
        passwordLabel.setBounds(262, 229, 75, 23);

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        add(passwordTextField);
        passwordTextField.setBounds(341, 231, 212, 20);

        pass2Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pass2Label.setText("Re Enter Password:");
        add(pass2Label);
        pass2Label.setBounds(196, 270, 141, 23);

        pass2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2TextFieldActionPerformed(evt);
            }
        });
        add(pass2TextField);
        pass2TextField.setBounds(341, 272, 212, 20);

        submitButton.setFont(new java.awt.Font("IrisUPC", 0, 36)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton);
        submitButton.setBounds(220, 336, 122, 34);

        resetLabel.setFont(new java.awt.Font("IrisUPC", 0, 36)); // NOI18N
        resetLabel.setText("RESET ");
        resetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLabelActionPerformed(evt);
            }
        });
        add(resetLabel);
        resetLabel.setBounds(492, 336, 103, 34);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void pass2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2TextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try(MongoClient mongoClient= new MongoClient("localhost",27017))
        {
            DB db=mongoClient.getDB("rpu");
            DBCollection dbCollection=db.getCollection("AllRegisteredCompanies");
            String nm=nameTextField.getText();
            String id=idTextField.getText();
            String pass=passwordTextField.getText();
            String repass=pass2TextField.getText();
            BasicDBObject db1=new BasicDBObject().append("username",id);
            DBCursor cur=dbCollection.find(db1);
            if(cur.hasNext())
            {
                JOptionPane.showMessageDialog(this, "Username already Exists");
            }
            else
            {
            if(pass.equals(repass))
            {
                try{
                    BasicDBObject dbObject=new BasicDBObject("company_name",nm);
                    dbObject.append("username",id);
                    dbObject.append("password",pass);
                    dbObject.append("accountType","Free");
                    dbCollection.insert(dbObject);
                    JOptionPane.showMessageDialog(this,"Registered Successfully");
                    nameTextField.setText("");
                    idTextField.setText("");
                    passwordTextField.setText("");
                    pass2TextField.setText("");
                }
                catch(Exception e){}
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Entered Passwords do not match");
            }
            }
        }catch(Exception e) {};
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void resetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLabelActionPerformed

        try{
            nameTextField.setText("");
            idTextField.setText("");
            passwordTextField.setText("");
            pass2TextField.setText("");

        }catch(Exception e) {};

    }//GEN-LAST:event_resetLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel pass2Label;
    private javax.swing.JPasswordField pass2TextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton resetLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
