/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BaZinGa
 */
public class CreditCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form creditCardPanel
     * @param parentFrame
     * @param companyName
     */
    public CreditCardPanel(JFrame parentFrame,String companyName) {
        this.parentFrame=parentFrame;
        initComponents();
        this.companyName=companyName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        creditCardNumberField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        slash = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PAY VIA CREDIT CARD");

        creditCardNumberField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        creditCardNumberField.setForeground(java.awt.Color.lightGray);
        creditCardNumberField.setText("Card Number");
        creditCardNumberField.setToolTipText("Card Number");
        creditCardNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        creditCardNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creditCardNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creditCardNumberFieldFocusLost(evt);
            }
        });
        creditCardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardNumberFieldActionPerformed(evt);
            }
        });
        creditCardNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditCardNumberFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditCardNumberFieldKeyTyped(evt);
            }
        });

        monthTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthTextField.setForeground(java.awt.Color.lightGray);
        monthTextField.setText("MM");
        monthTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        monthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusLost(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        monthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthTextFieldKeyTyped(evt);
            }
        });

        slash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        slash.setText("/");

        yearTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearTextField.setForeground(java.awt.Color.lightGray);
        yearTextField.setText("YY");
        yearTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusLost(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        yearTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTextFieldKeyTyped(evt);
            }
        });

        cvvTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cvvTextField.setForeground(java.awt.Color.lightGray);
        cvvTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cvvTextField.setText("CVV");
        cvvTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cvvTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cvvTextFieldFocusLost(evt);
            }
        });
        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        cvvTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyTyped(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameTextField.setForeground(java.awt.Color.lightGray);
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextField.setText("Card Holder's Name");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitButton.setText("Pay Now");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creditCardNumberField)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(submitButton)
                        .addGap(38, 38, 38)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(81, 81, 81))
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(creditCardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(slash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearTextField)
                    .addComponent(cvvTextField)
                    .addComponent(monthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creditCardNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditCardNumberFieldFocusGained
        // TODO add your handling code here:
        if(this.creditCardNumberField.getText().equals("Card Number")){
            this.creditCardNumberField.setText("");
            this.creditCardNumberField.setForeground(Color.BLACK);
        }
        else
            
            this.creditCardNumberField.selectAll();
        
    }//GEN-LAST:event_creditCardNumberFieldFocusGained

    private void creditCardNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditCardNumberFieldFocusLost
        // TODO add your handling code here:
        if(this.creditCardNumberField.getText().equals(""))
        {
            this.creditCardNumberField.setForeground(Color.LIGHT_GRAY);
            this.creditCardNumberField.setText("Card Number");
        }
        
    }//GEN-LAST:event_creditCardNumberFieldFocusLost

    private void creditCardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardNumberFieldActionPerformed

    private void monthTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusGained
        // TODO add your handling code here:
        if(this.monthTextField.getText().equals("MM")){
            this.monthTextField.setText("");
            this.monthTextField.setForeground(Color.black);
        }
        else this.monthTextField.selectAll();
    }//GEN-LAST:event_monthTextFieldFocusGained

    private void monthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusLost
        // TODO add your handling code here:
        if(this.monthTextField.getText().equals(""))
        {
            this.monthTextField.setForeground(Color.LIGHT_GRAY);
            this.monthTextField.setText("MM");
        }
    }//GEN-LAST:event_monthTextFieldFocusLost

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void yearTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusGained
        // TODO add your handling code here:
        if(this.yearTextField.getText().equals("YY")){
            this.yearTextField.setText("");
            this.yearTextField.setForeground(Color.black);
        }
        else yearTextField.selectAll();
    }//GEN-LAST:event_yearTextFieldFocusGained

    private void yearTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusLost
        // TODO add your handling code here:
        if(this.yearTextField.getText().equals(""))
        {
            this.yearTextField.setForeground(Color.LIGHT_GRAY);
            this.yearTextField.setText("YY");
        }
    }//GEN-LAST:event_yearTextFieldFocusLost

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void cvvTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvvTextFieldFocusGained
        // TODO add your handling code here:
        if(this.cvvTextField.getText().equals("CVV")){
            this.cvvTextField.setText("");
            this.cvvTextField.setForeground(Color.black);
        }
        else cvvTextField.selectAll();
    }//GEN-LAST:event_cvvTextFieldFocusGained

    private void cvvTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvvTextFieldFocusLost
        // TODO add your handling code here:
        if(this.cvvTextField.getText().equals(""))
        {
            this.cvvTextField.setForeground(Color.LIGHT_GRAY);
            this.cvvTextField.setText("YY");
        }
    }//GEN-LAST:event_cvvTextFieldFocusLost

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(this.creditCardNumberField.getText().equals("Card Number")
            ||this.monthTextField.getText().equals("MM")
            ||this.yearTextField.getText().equals("YY")
            ||this.cvvTextField.getText().equals("CVV")
            ||this.nameTextField.getText().equals("Card Holder's Name")){
            JOptionPane.showMessageDialog(this, "One or More Fields are Required!!!");
            System.out.println("javaapplication1.CreditCardPanel.submitButtonActionPerformed()"+"inside while");
        }
        else{
            try(MongoClient mongoClient = new MongoClient("localhost",27017)) {
                DB db=mongoClient.getDB("rpu");
                DBCollection dBCollection=db.getCollection("payments");
                BasicDBObject basicDBObject=new BasicDBObject("CompanyName",this.companyName);
                SimpleDateFormat simpleDateFormat =new SimpleDateFormat("dd:MM:yyyy");
                Date date=new Date();
                basicDBObject.append("dateofPayment",simpleDateFormat.format(date));
                Calendar calendar=Calendar.getInstance();
                calendar.setTime(date);
                calendar.add(Calendar.DAY_OF_MONTH ,1);
                date=calendar.getTime();
                basicDBObject.append("dateofExpiry",simpleDateFormat.format(date));
                basicDBObject.append("PaymentMethod","creditCard");
                dBCollection.insert(basicDBObject);
                dBCollection=db.getCollection("AllRegisteredCompanies");
                basicDBObject=new BasicDBObject("$set",new BasicDBObject("accountType","Paid"));
                BasicDBObject findBy=new BasicDBObject("company_name",this.companyName);
                dBCollection.update(findBy, basicDBObject);
                JOptionPane.showMessageDialog(this, "Payment Complete!!!");
                this.setVisible(false);
                CompanyPage companyPage=new CompanyPage(this.companyName,"Paid");
                companyPage.setVisible(true);
                this.parentFrame.setVisible(false);
                this.parentFrame.dispose();
            }catch(Exception e){
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(paymentPanel, e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameTextFieldActionPerformed
                                       
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        this.creditCardNumberField.setForeground(Color.lightGray);
        this.creditCardNumberField.setText("Card Number");
        this.monthTextField.setForeground(Color.lightGray);
        this.monthTextField.setText("MM");
        this.yearTextField.setForeground(Color.lightGray);
        this.yearTextField.setText("YY");
        this.cvvTextField.setForeground(Color.lightGray);
        this.cvvTextField.setText("CVV");
        this.nameTextField.setForeground(Color.lightGray);
        this.nameTextField.setText("Card Holder's Name");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        // TODO add your handling code here:
        if(this.nameTextField.getText().equals("Card Holder's Name")){
            this.nameTextField.setText("");
            this.nameTextField.setForeground(Color.black);
        }
        else this.nameTextField.selectAll();
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        // TODO add your handling code here:
        if(this.nameTextField.getText().equals(""))
        {
            this.nameTextField.setForeground(Color.LIGHT_GRAY);
            this.nameTextField.setText("Card Holder's Name");
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    
    
    private void creditCardNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditCardNumberFieldKeyPressed
        // TODO add your handling code here:
   
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
        { evt.consume();
        }
    
    }//GEN-LAST:event_creditCardNumberFieldKeyPressed

    private void creditCardNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditCardNumberFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
        { evt.consume();
        }
    }//GEN-LAST:event_creditCardNumberFieldKeyTyped

    private void monthTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_monthTextFieldKeyTyped

    private void yearTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTextFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_yearTextFieldKeyTyped

    private void cvvTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_cvvTextFieldKeyTyped
          
    private JFrame parentFrame;
    private String companyName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField creditCardNumberField;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel slash;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}