/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * author BaZinGa
 */
public class DebitCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form debitCardPanel
     * @param parentFrame
     * @param companyName
     */
    public DebitCardPanel(JFrame parentFrame,String companyName){
        initComponents();
        this.parentFrame=parentFrame;
        this.companyName=companyName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        paymentPanel = new javax.swing.JPanel();
        debitCardNumberField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        slash = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        creditcardErrorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        debitCardNumberField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        debitCardNumberField.setForeground(java.awt.Color.lightGray);
        debitCardNumberField.setText("Card Number");
        debitCardNumberField.setToolTipText("Card Number");
        debitCardNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        debitCardNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                debitCardNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                debitCardNumberFieldFocusLost(evt);
            }
        });
        debitCardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitCardNumberFieldActionPerformed(evt);
            }
        });
        debitCardNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                debitCardNumberFieldKeyTyped(evt);
            }
        });

        monthTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthTextField.setForeground(java.awt.Color.lightGray);
        monthTextField.setText("MM");
        monthTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        monthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusLost(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        monthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthTextFieldKeyTyped(evt);
            }
        });

        slash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        slash.setText("/");

        yearTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearTextField.setForeground(java.awt.Color.lightGray);
        yearTextField.setText("YY");
        yearTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusLost(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        yearTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTextFieldKeyTyped(evt);
            }
        });

        cvvTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cvvTextField.setForeground(java.awt.Color.lightGray);
        cvvTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cvvTextField.setText("CVV");
        cvvTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cvvTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cvvTextFieldFocusLost(evt);
            }
        });
        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        cvvTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvTextFieldKeyTyped(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameTextField.setForeground(java.awt.Color.lightGray);
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextField.setText("Card Holder's Name");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitButton.setText("Pay Now");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PAY VIA DEBIT CARD");

        creditcardErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(debitCardNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(creditcardErrorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(submitButton)
                            .addGap(38, 38, 38)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditcardErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(debitCardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(slash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearTextField)
                    .addComponent(cvvTextField)
                    .addComponent(monthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void validate(){
        StringBuffer errorMessage=new StringBuffer("Invalid");
        Pattern pattern=Pattern.compile("\\d{16}");
        Matcher matcher=pattern.matcher(this.debitCardNumberField.getText());
        if(matcher.matches()==false)
           errorMessage.append(" "+"Credit Card Number");
    }
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if(this.debitCardNumberField.getText().equals("Card Number")
            ||this.monthTextField.getText().equals("MM")
            ||this.yearTextField.getText().equals("YY")
            ||this.cvvTextField.getText().equals("CVV")
            ||this.nameTextField.getText().equals("Card Holder's Name")){
            JOptionPane.showMessageDialog(this, "One or More Fields are Required!!!");
        }
        else{               
            try(MongoClient mongoClient = new MongoClient("localhost",27017)) {
                DB db=mongoClient.getDB("rpu");
                DBCollection dBCollection=db.getCollection("payments");
                BasicDBObject basicDBObject=new BasicDBObject("CompanyName",this.companyName);
                SimpleDateFormat simpleDateFormat =new SimpleDateFormat("dd:MM:yyyy");
                Date date=new Date();
                basicDBObject.append("dateofPayment",simpleDateFormat.format(date));
                Calendar calendar=Calendar.getInstance();
                calendar.setTime(date);
                calendar.add(Calendar.DAY_OF_MONTH ,1);
                date=calendar.getTime();
                basicDBObject.append("dateofExpiry",simpleDateFormat.format(date));
                basicDBObject.append("PaymentMethod","debitcard");
                dBCollection.insert(basicDBObject);
                dBCollection=db.getCollection("AllRegisteredCompanies");
                basicDBObject=new BasicDBObject("$set",new BasicDBObject("accountType","Paid"));
                BasicDBObject findBy=new BasicDBObject("company_name",this.companyName);
                dBCollection.update(findBy, basicDBObject);
                JOptionPane.showMessageDialog(this, "Payment Complete!!!");
                this.setVisible(false);
                CompanyPage companyPage=new CompanyPage(this.companyName,"Paid");
                companyPage.setVisible(true);
                this.parentFrame.setVisible(false);
                this.parentFrame.dispose();
            }catch(Exception e){
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(paymentPanel, e.getMessage());
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void debitCardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitCardNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitCardNumberFieldActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        this.debitCardNumberField.setForeground(Color.lightGray);
        this.debitCardNumberField.setText("Card Number");
        this.monthTextField.setForeground(Color.lightGray);
        this.monthTextField.setText("MM");
        this.yearTextField.setForeground(Color.lightGray);
        this.yearTextField.setText("YY");
        this.cvvTextField.setForeground(Color.lightGray);
        this.cvvTextField.setText("CVV");
        this.nameTextField.setForeground(Color.lightGray);
        this.nameTextField.setText("Card Holder's Name");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void debitCardNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_debitCardNumberFieldFocusGained
        // TODO add your handling code here:
        if(this.debitCardNumberField.getText().equals("Card Number")){
            this.debitCardNumberField.setText("");
            this.debitCardNumberField.setForeground(Color.BLACK);
        }
        else this.debitCardNumberField.selectAll();
    }//GEN-LAST:event_debitCardNumberFieldFocusGained

    private void debitCardNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_debitCardNumberFieldFocusLost
        // TODO add your handling code here:
        if(this.debitCardNumberField.getText().equals(""))
        {
            this.debitCardNumberField.setForeground(Color.LIGHT_GRAY);
            this.debitCardNumberField.setText("Card Number");
        }
    }//GEN-LAST:event_debitCardNumberFieldFocusLost

    private void monthTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusGained
        // TODO add your handling code here:
        if(this.monthTextField.getText().equals("MM")){
            this.monthTextField.setText("");
            this.monthTextField.setForeground(Color.black);         
        }
        else this.monthTextField.selectAll();
    }//GEN-LAST:event_monthTextFieldFocusGained

    private void monthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusLost
        // TODO add your handling code here:
        if(this.monthTextField.getText().equals(""))
        {
            this.monthTextField.setForeground(Color.LIGHT_GRAY);
            this.monthTextField.setText("MM");
        }
    }//GEN-LAST:event_monthTextFieldFocusLost

    private void yearTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusGained
        // TODO add your handling code here:
        if(this.yearTextField.getText().equals("YY")){
            this.yearTextField.setText("");
            this.yearTextField.setForeground(Color.black);
        }
        else yearTextField.selectAll();
    }//GEN-LAST:event_yearTextFieldFocusGained

    private void yearTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusLost
        // TODO add your handling code here:
        if(this.yearTextField.getText().equals(""))
        {
            this.yearTextField.setForeground(Color.LIGHT_GRAY);
            this.yearTextField.setText("YY");
        }
    }//GEN-LAST:event_yearTextFieldFocusLost

    private void cvvTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvvTextFieldFocusGained
        // TODO add your handling code here:
        if(this.cvvTextField.getText().equals("CVV")){
            this.cvvTextField.setText("");
            this.cvvTextField.setForeground(Color.black);
        }
        else cvvTextField.selectAll();
    }//GEN-LAST:event_cvvTextFieldFocusGained

    private void cvvTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvvTextFieldFocusLost
        // TODO add your handling code here:
        if(this.cvvTextField.getText().equals(""))
        {
            this.cvvTextField.setForeground(Color.LIGHT_GRAY);
            this.cvvTextField.setText("CVV");
        }
    }//GEN-LAST:event_cvvTextFieldFocusLost

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        // TODO add your handling code here:
        if(this.nameTextField.getText().equals("Card Holder's Name")){
            this.nameTextField.setText("");
            this.nameTextField.setForeground(Color.black);
        }
        else this.nameTextField.selectAll();
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        // TODO add your handling code here:
        if(this.nameTextField.getText().equals(""))
        {
            this.nameTextField.setForeground(Color.LIGHT_GRAY);
            this.nameTextField.setText("Card Holder's Name");
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void debitCardNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitCardNumberFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
        
    }//GEN-LAST:event_debitCardNumberFieldKeyTyped

    private void cvvTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
        
    }//GEN-LAST:event_cvvTextFieldKeyTyped

    private void yearTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_yearTextFieldKeyTyped

    private void monthTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthTextFieldKeyTyped
        // TODO add your handling code here:
        //Integer month=Integer.parseInt(this.monthTextField.getText().toString());
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_monthTextFieldKeyTyped
                                   
    private JFrame parentFrame;
    private String companyName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditcardErrorLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JTextField debitCardNumberField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel slash;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
