/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
    */
    
    public LoginScreen() {
        initComponents();
        this.setSize(802,519);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.jLabel2.setVisible(true);
    }
    ArrayList<JPanel> pn=new <JPanel>ArrayList();
    public void hideOtherPanels()
    {
        Iterator<JPanel> pan=pn.iterator();
        while(pan.hasNext()){
            JPanel jPanel=pan.next();
            jPanel.setVisible(false);
            this.remove(jPanel);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CandidateMenu = new javax.swing.JMenu();
        CandidateLoginMenuItem = new javax.swing.JMenuItem();
        CandidateRegMenuItem = new javax.swing.JMenuItem();
        CompanyMenu = new javax.swing.JMenu();
        CompanyLoginMenuItem = new javax.swing.JMenuItem();
        CompanyRegMenuItem = new javax.swing.JMenuItem();
        CloseMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Recruitment Process Unit");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 0, 212, 46);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/panel-interview.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 800, 510);

        jMenu1.setText("Login");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        CandidateMenu.setText("Candidate");
        CandidateMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CandidateLoginMenuItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        CandidateLoginMenuItem.setText("Login");
        CandidateLoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateLoginMenuItemActionPerformed(evt);
            }
        });
        CandidateMenu.add(CandidateLoginMenuItem);

        CandidateRegMenuItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        CandidateRegMenuItem.setText("Register");
        CandidateRegMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateRegMenuItemActionPerformed(evt);
            }
        });
        CandidateMenu.add(CandidateRegMenuItem);

        jMenu1.add(CandidateMenu);

        CompanyMenu.setText("Company");
        CompanyMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CompanyLoginMenuItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        CompanyLoginMenuItem.setText("Login");
        CompanyLoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLoginMenuItemActionPerformed(evt);
            }
        });
        CompanyMenu.add(CompanyLoginMenuItem);

        CompanyRegMenuItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        CompanyRegMenuItem.setText("Register");
        CompanyRegMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRegMenuItemActionPerformed(evt);
            }
        });
        CompanyMenu.add(CompanyRegMenuItem);

        jMenu1.add(CompanyMenu);

        CloseMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CloseMenuItem.setText("Close");
        CloseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CloseMenuItem);

        MainMenuBar.add(jMenu1);

        setJMenuBar(MainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CandidateLoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateLoginMenuItemActionPerformed
                this.hideOtherPanels();
                CandidateLogin  CL=new CandidateLogin(this);
                this.pn.add(CL);
                this.jLabel2.setVisible(false);
                CL.setBounds(0,0,802,519);
                add(CL);
                this.revalidate();
                this.repaint();
               
    }//GEN-LAST:event_CandidateLoginMenuItemActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void CompanyLoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLoginMenuItemActionPerformed
            this.hideOtherPanels();
            CompanyLoginPage j1=new CompanyLoginPage(this);
            this.pn.add(j1);
            j1.setBounds(0, 0, 802, 519);
            add(j1);
            this.jLabel2.setVisible(false);
            this.revalidate();
            this.repaint();
    }//GEN-LAST:event_CompanyLoginMenuItemActionPerformed

    private void CandidateRegMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateRegMenuItemActionPerformed
            this.hideOtherPanels();
            CandidateRegisterForm c1=new CandidateRegisterForm();
            this.pn.add(c1);
            c1.setBounds(0, 0, 802, 519);
            add(c1);
            this.jLabel2.setVisible(false);
            
            this.revalidate();
            this.repaint();
            
    }//GEN-LAST:event_CandidateRegMenuItemActionPerformed

    private void CloseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseMenuItemActionPerformed
        try{
            Process process=Runtime.getRuntime().exec("stopserver.bat");
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, e);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CloseMenuItemActionPerformed

    private void CompanyRegMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyRegMenuItemActionPerformed
            this.hideOtherPanels();
            companyRegistration c1=new companyRegistration();
            this.pn.add(c1);
            c1.setBounds(0, 0, 802, 519);
            add(c1);
            this.jLabel2.setVisible(false);
            this.revalidate();
            this.repaint();
            // TODO add your handling code here:
    }//GEN-LAST:event_CompanyRegMenuItemActionPerformed

    /**
     * @param args the command line arguments    */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        })
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem CandidateLoginMenuItem;
    private javax.swing.JMenu CandidateMenu;
    private javax.swing.JMenuItem CandidateRegMenuItem;
    private javax.swing.JMenuItem CloseMenuItem;
    private javax.swing.JMenuItem CompanyLoginMenuItem;
    private javax.swing.JMenu CompanyMenu;
    private javax.swing.JMenuItem CompanyRegMenuItem;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
