/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author BaZinGa
 */
public class SubmitQuestionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form submitQuestionsFrame
     * @param parentPanel
     * @param companyName
     */
    public SubmitQuestionsFrame(JPanel parentPanel,String companyName) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.parentPanel=parentPanel;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        qlrRadioButton = new javax.swing.JRadioButton();
        cJavaRadioButton = new javax.swing.JRadioButton();
        frameworksRadioButton = new javax.swing.JRadioButton();
        androidRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        ansBTextField = new javax.swing.JTextField();
        ansATextField = new javax.swing.JTextField();
        ansCTextField = new javax.swing.JTextField();
        ansDTextField = new javax.swing.JTextField();
        correctAnsTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        qlrRadioButton.setText("QLR");
        qlrRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlrRadioButtonActionPerformed(evt);
            }
        });

        cJavaRadioButton.setText("Core JAVA");
        cJavaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJavaRadioButtonActionPerformed(evt);
            }
        });

        frameworksRadioButton.setText("Frameworks");
        frameworksRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameworksRadioButtonActionPerformed(evt);
            }
        });

        androidRadioButton.setText("Android");
        androidRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                androidRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Question :");

        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        questionTextArea.setRows(5);
        jScrollPane1.setViewportView(questionTextArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ans :");

        ansBTextField.setFont(new java.awt.Font("NSimSun", 3, 12)); // NOI18N
        ansBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBTextFieldActionPerformed(evt);
            }
        });

        ansATextField.setFont(new java.awt.Font("NSimSun", 3, 12)); // NOI18N

        ansCTextField.setFont(new java.awt.Font("NSimSun", 3, 12)); // NOI18N

        ansDTextField.setFont(new java.awt.Font("NSimSun", 3, 12)); // NOI18N

        correctAnsTextField.setFont(new java.awt.Font("NSimSun", 3, 12)); // NOI18N

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Correct Ans. :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("C.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("D.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("B.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("A.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ansDTextField)
                    .addComponent(ansCTextField)
                    .addComponent(ansBTextField)
                    .addComponent(ansATextField)
                    .addComponent(correctAnsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qlrRadioButton)
                .addGap(18, 18, 18)
                .addComponent(cJavaRadioButton)
                .addGap(18, 18, 18)
                .addComponent(frameworksRadioButton)
                .addGap(18, 18, 18)
                .addComponent(androidRadioButton)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qlrRadioButton)
                                    .addComponent(cJavaRadioButton)
                                    .addComponent(frameworksRadioButton)
                                    .addComponent(androidRadioButton)
                                    .addComponent(backButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ansATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ansBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ansCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ansDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correctAnsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.revalidate();
        this.repaint();
        this.parentPanel.setVisible(true);
        this.parentPanel.revalidate();
        this.parentPanel.repaint();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void qlrRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlrRadioButtonActionPerformed
        // TODO add your handling code here:
        this.typeOfQuestion="qlrquiz";
    }//GEN-LAST:event_qlrRadioButtonActionPerformed

    private void cJavaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJavaRadioButtonActionPerformed
        // TODO add your handling code here:
        this.typeOfQuestion="cjavaquiz";
    }//GEN-LAST:event_cJavaRadioButtonActionPerformed

    private void frameworksRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameworksRadioButtonActionPerformed
        // TODO add your handling code here:
        this.typeOfQuestion="framequiz";
    }//GEN-LAST:event_frameworksRadioButtonActionPerformed

    private void androidRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_androidRadioButtonActionPerformed
        // TODO add your handling code here:
        this.typeOfQuestion="andquiz";
    }//GEN-LAST:event_androidRadioButtonActionPerformed

    private void ansBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansBTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(this.questionTextArea.getText().equals("")
            ||this.ansATextField.getText().equals("")
            ||this.ansBTextField.getText().equals("")
            ||this.ansCTextField.getText().equals("")
            ||this.ansDTextField.getText().equals("")
            ||this.correctAnsTextField.getText().equals("")
            ||this.typeOfQuestion==null)
            JOptionPane.showMessageDialog(this, "One Or More Fileds are Empty");
        else{
            try{
                try (MongoClient mongoClient = new MongoClient("localhost",27017)) {
                    DB db=mongoClient.getDB("rpu");
                    DBCollection dBCollection=db.getCollection(typeOfQuestion);
                    BasicDBObject basicDBObject=new BasicDBObject("question",this.questionTextArea.getText())
                            .append("optA",this.ansATextField.getText())
                            .append("optB",this.ansBTextField.getText())
                            .append("optC",this.ansCTextField.getText())
                            .append("optD",this.ansDTextField.getText())
                            .append("answer",this.correctAnsTextField.getText());
                    dBCollection.insert(basicDBObject);
                    JOptionPane.showMessageDialog(this, "Question Submitted Sucessfully!");
                }
            }catch(Exception E){
                System.out.println(E.getMessage());
            }
            this.questionTextArea.setText("");
            this.ansATextField.setText("");
            this.ansBTextField.setText("");
            this.ansCTextField.setText("");
            this.ansDTextField.setText("");
            this.correctAnsTextField.setText("");
            this.buttonGroup.clearSelection();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private ButtonGroup buttonGroup;
    private JPanel parentPanel;
    private String companyName,typeOfQuestion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton androidRadioButton;
    private javax.swing.JTextField ansATextField;
    private javax.swing.JTextField ansBTextField;
    private javax.swing.JTextField ansCTextField;
    private javax.swing.JTextField ansDTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton cJavaRadioButton;
    private javax.swing.JTextField correctAnsTextField;
    private javax.swing.JRadioButton frameworksRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton qlrRadioButton;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
